train: /root/workspace/s7/datasets/vfn-yolo/train/images
val: /root/workspace/s7/datasets/vfn-yolo/test/images

names:
  0: almonds
  1: apple
  2: apple_pie
  3: apple_sauce
  4: avocado
  5: bacon
  6: bagel
  7: baked_beans
  8: baked_potato
  9: bananas
  10: beer
  11: biscuit
  12: black_beans
  13: blueberries
  14: boiled_egg
  15: breaded_fish
  16: broccoli
  17: brown_rice
  18: brownie
  19: burrito
  20: cabbage
  21: cake
  22: cantaloupe
  23: carrot
  24: cheese_burger
  25: cheese_sandwiches
  26: chicken_breast
  27: chicken_nugget
  28: chicken_tender
  29: chicken_thigh
  30: chicken_wing
  31: chips
  32: chocolate_milk
  33: cinnamon_bun
  34: coleslaw
  35: cookie
  36: corn
  37: cornbread
  38: croissant
  39: cupcake
  40: doughnut
  41: french_fries
  42: french_toast
  43: fried_egg
  44: fried_rice
  45: fruit_drink
  46: green_beans
  47: grilled_salmon
  48: hash_brown
  49: hot_dog
  50: ice_cream
  51: lasagna
  52: mac_and_cheese
  53: mashed_potatoes
  54: meat_loaf
  55: milk
  56: muffin
  57: omelet
  58: pancake
  59: pasta
  60: pizza
  61: pork_chop
  62: pork_rib
  63: quesadilla
  64: red_wine
  65: shrimp
  66: soup
  67: steak
  68: stew_beef
  69: strawberries
  70: sushi
  71: taco
  72: tomatoes
  73: tortillas
  74: tostada
  75: tuna_salad
  76: turkey
  77: waffle
  78: white_rice
  79: white_wine
  80: yeast_bread
  81: yogurt